# Generated by Django 5.0.2 on 2024-03-03 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='passRate',
            new_name='pass_rate',
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(max_length=1000)),
                ('explanation', models.CharField(max_length=2000)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.test')),
            ],
        ),
    ]
