# Generated by Django 5.0.2 on 2024-03-17 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0002_alter_multiplechoiceanswers_is_correct'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiceResult',
            fields=[
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Web.questionresult')),
            ],
        ),
        migrations.CreateModel(
            name='SingleChoiceResult',
            fields=[
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Web.questionresult')),
                ('chose', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=-1)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Web.test')),
            ],
        ),
        migrations.AddField(
            model_name='questionresult',
            name='user_answers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.useranswers'),
        ),
        migrations.CreateModel(
            name='MultipleChoiceAnswersResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_chose', models.BooleanField()),
                ('multiple_choice_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.multiplechoiceresult')),
            ],
        ),
    ]
