# Generated by Django 5.0.2 on 2024-03-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0002_rename_createdat_test_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='pass_rate',
            field=models.IntegerField(default=0),
        ),
    ]
