# Generated by Django 5.0.2 on 2024-03-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0003_questionresult_multiplechoiceresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswers',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
