# Generated by Django 5.0.2 on 2024-03-03 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0003_alter_test_pass_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='pass_rate',
        ),
        migrations.CreateModel(
            name='MultipleChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.question')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiceAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('is_correct', models.BooleanField()),
                ('multiple_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.multiplechoice')),
            ],
        ),
        migrations.CreateModel(
            name='SingleChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.question')),
            ],
        ),
        migrations.CreateModel(
            name='SingleChoiceAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('single_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.singlechoice')),
            ],
        ),
    ]
