# Generated by Django 5.0.2 on 2024-03-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0004_remove_test_pass_rate_multiplechoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
