# Generated by Django 5.0.2 on 2024-03-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0004_useranswers_is_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplechoiceanswersresult',
            name='is_chose',
        ),
        migrations.AddField(
            model_name='multiplechoiceanswersresult',
            name='chose',
            field=models.IntegerField(default=-1),
        ),
    ]
