# Generated by Django 5.0.2 on 2024-04-17 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0004_alter_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='pass_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='published_at',
            field=models.DateField(default=datetime.date(2024, 4, 17)),
        ),
    ]
