# Generated by Django 5.0.2 on 2024-04-25 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0005_test_pass_rate_test_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='published_at',
            field=models.DateField(default=datetime.datetime(2024, 4, 25, 19, 35, 57, 7262, tzinfo=datetime.timezone.utc)),
        ),
    ]
