# Generated by Django 5.0.2 on 2024-03-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0005_alter_question_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choice_type',
            field=models.IntegerField(default=0),
        ),
    ]
