# Generated by Django 5.0.2 on 2024-03-22 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0005_remove_multiplechoiceanswersresult_is_chose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswers',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.test'),
        ),
    ]
