# Generated by Django 5.0.2 on 2024-03-03 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0006_question_choice_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='explanation',
        ),
    ]
