# Generated by Django 5.0.2 on 2024-03-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0006_alter_useranswers_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresult',
            name='question_id',
            field=models.IntegerField(default=-1),
        ),
    ]
