# Generated by Django 5.0.2 on 2024-04-28 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0006_alter_test_published_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='test',
            name='published_at',
            field=models.DateField(default=datetime.datetime(2024, 4, 28, 18, 21, 2, 117647, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='test',
            name='tags',
            field=models.ManyToManyField(to='Web.tags'),
        ),
    ]
