# Generated by Django 5.0.2 on 2024-03-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0007_remove_question_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
