# Generated by Django 5.0.2 on 2024-04-29 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0007_tags_alter_test_published_at_test_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswers',
            name='finished_at',
            field=models.DateField(default=datetime.datetime(2024, 4, 29, 14, 42, 34, 443989, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='test',
            name='published_at',
            field=models.DateField(default=datetime.datetime(2024, 4, 29, 14, 42, 34, 441988, tzinfo=datetime.timezone.utc)),
        ),
    ]
