# Generated by Django 5.0.2 on 2024-04-29 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0008_useranswers_finished_at_alter_test_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='published_at',
            field=models.DateField(default=datetime.datetime(2024, 4, 29, 14, 47, 40, 140410, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='finished_at',
            field=models.DateField(default=datetime.datetime(2024, 4, 29, 17, 47, 40, 142443)),
        ),
    ]
