# Generated by Django 5.0.2 on 2024-04-29 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0009_alter_test_published_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='published_at',
            field=models.DateField(default=datetime.datetime(2024, 4, 29, 14, 48, 58, 255591, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='finished_at',
            field=models.DateField(default=datetime.datetime(2024, 4, 29, 14, 48, 58, 257591, tzinfo=datetime.timezone.utc)),
        ),
    ]
