# Generated by Django 5.0.2 on 2024-04-30 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0012_remove_test_correct_rate_all_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='published_at',
            field=models.DateField(default=datetime.datetime(2024, 4, 30, 16, 36, 43, 347666, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='correct_answer_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='correct_answers',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='finished_at',
            field=models.DateField(default=datetime.datetime(2024, 4, 30, 16, 36, 43, 350631, tzinfo=datetime.timezone.utc)),
        ),
    ]
