# Generated by Django 5.0.2 on 2024-04-30 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0014_alter_test_published_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlechoiceresult',
            name='chose',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='test',
            name='created_at',
            field=models.DateField(default=datetime.date(2024, 4, 30)),
        ),
        migrations.AlterField(
            model_name='test',
            name='published_at',
            field=models.DateField(default=datetime.date(2024, 4, 30)),
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='finished_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 19, 52, 10, 375060)),
        ),
    ]
