# Generated by Django 5.0.2 on 2024-05-01 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0016_alter_singlechoice_correct_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionresult',
            name='question_id',
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='finished_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 1, 17, 56, 52, 855600)),
        ),
    ]
