# Generated by Django 5.0.2 on 2024-05-01 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0017_remove_questionresult_question_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoice',
            name='total_count',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='multiplechoiceanswers',
            name='count',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='singlechoiceanswers',
            name='count',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='finished_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 1, 19, 30, 1, 902427)),
        ),
    ]
