# Generated by Django 5.0.4 on 2024-05-02 02:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Web", "0019_alter_multiplechoice_total_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="created_at",
            field=models.DateField(default=datetime.date(2024, 5, 2)),
        ),
        migrations.AlterField(
            model_name="test",
            name="published_at",
            field=models.DateField(default=datetime.date(2024, 5, 2)),
        ),
        migrations.AlterField(
            model_name="useranswers",
            name="finished_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 2, 5, 18, 8, 839162)
            ),
        ),
    ]
